apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: foo-service
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 9090
    targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-service
spec:
  selector:
    matchLabels:
      app: foo-service
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: foo-service
        tier: frontend
        track: stable
    spec:
      containers:
      - name: foo-service
        image: aweeraman/foo-service
        ports:
        - containerPort: 9090
