apiVersion: v1
kind: Service
metadata:
  name: foo-service
  labels:
    app: foo-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: 9090
    nodePort: 30001
  selector:
    app: foo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-service
spec:
  selector:
    matchLabels:
      app: foo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: foo-service
    spec:
      containers:
      - name: foo-service
        image: aweeraman/foo-service
        ports:
        - containerPort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /foo/.*
        backend:
          serviceName: foo-service
          servicePort: 9090
